# Generated by Django 3.2.2 on 2021-10-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pair',
            field=models.CharField(max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.IntegerField(choices=[(0, 'BUY'), (1, 'SELL')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddresses',
            name='currency',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='blockchain.useraddresses'),
        ),
    ]
